# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  vkakb:
    image: vkakb
    build:
      context: .
      dockerfile: VkAkb/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5245:5245
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
